application: evchargesites
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /
  script: main.py

- url: /rpc
  script: rpc.py

- url: /import[/]?
  script: import.py
  login: admin

